In [10]:
from core.labels import MultilabelLabeler

labeler = MultilabelLabeler()
labeler.collect(['B', 'A'])
labeler.collect(['B', 'C'])
labeler.collect(['A'])
labeler.collect(['D', 'E', 'F'])

labeler.fit()

In [11]:
print(labeler.vectorize(['A', 'B']))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]]


In [12]:
print(labeler.vectorize(['A', 'F']))

[[1 0 0 0 0 0]
 [0 0 0 0 0 1]]


In [13]:
import numpy as np
from sklearn.metrics import ndcg_score

# Sample true labels (ground truth)
y_true = np.array([
    [1, 0, 1, 0],
    [0, 1, 1, 1],
    [1, 1, 0, 1]
])

# Sample predicted scores
y_score = np.array([
    [0.9, 0.2, 0.8, 0.1],
    [0.1, 0.7, 0.9, 0.5],
    [0.8, 0.9, 0.3, 0.6]
])

# Compute nDCG for each sample
ndcg_scores = []
for i in range(y_true.shape[0]):
    score = ndcg_score(y_true[i:i+1], y_score[i:i+1])
    ndcg_scores.append(score)

# Calculate average nDCG
average_ndcg = np.mean(ndcg_scores)

print("nDCG scores for each sample:", ndcg_scores)
print("Average nDCG:", average_ndcg)

# Compute nDCG for the entire dataset
overall_ndcg = ndcg_score(y_true, y_score)
print("Overall nDCG:", overall_ndcg)

nDCG scores for each sample: [1.0, 1.0, 1.0]
Average nDCG: 1.0
Overall nDCG: 1.0
